name: Publish Package to NPM

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --access public 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOPPASS_NPM_TOKEN }}
